//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.JacoArm
{
    [Serializable]
    public class ArmCommandMsg : Message
    {
        public const string k_RosMessageName = "jaco_arm/ArmCommand";
        public override string RosMessageName => k_RosMessageName;

        public string command;
        public string planner;
        public string joint_to_move;
        public float joint_1;
        public float joint_2;
        public float joint_3;
        public float joint_4;
        public float joint_5;
        public float joint_6;
        public float goal_x;
        public float goal_y;
        public float goal_z;

        public ArmCommandMsg()
        {
            this.command = "";
            this.planner = "";
            this.joint_to_move = "";
            this.joint_1 = 0.0f;
            this.joint_2 = 0.0f;
            this.joint_3 = 0.0f;
            this.joint_4 = 0.0f;
            this.joint_5 = 0.0f;
            this.joint_6 = 0.0f;
            this.goal_x = 0.0f;
            this.goal_y = 0.0f;
            this.goal_z = 0.0f;
        }

        public ArmCommandMsg(string command, string planner, string joint_to_move, float joint_1, float joint_2, float joint_3, float joint_4, float joint_5, float joint_6, float goal_x, float goal_y, float goal_z)
        {
            this.command = command;
            this.planner = planner;
            this.joint_to_move = joint_to_move;
            this.joint_1 = joint_1;
            this.joint_2 = joint_2;
            this.joint_3 = joint_3;
            this.joint_4 = joint_4;
            this.joint_5 = joint_5;
            this.joint_6 = joint_6;
            this.goal_x = goal_x;
            this.goal_y = goal_y;
            this.goal_z = goal_z;
        }

        public static ArmCommandMsg Deserialize(MessageDeserializer deserializer) => new ArmCommandMsg(deserializer);

        private ArmCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.command);
            deserializer.Read(out this.planner);
            deserializer.Read(out this.joint_to_move);
            deserializer.Read(out this.joint_1);
            deserializer.Read(out this.joint_2);
            deserializer.Read(out this.joint_3);
            deserializer.Read(out this.joint_4);
            deserializer.Read(out this.joint_5);
            deserializer.Read(out this.joint_6);
            deserializer.Read(out this.goal_x);
            deserializer.Read(out this.goal_y);
            deserializer.Read(out this.goal_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command);
            serializer.Write(this.planner);
            serializer.Write(this.joint_to_move);
            serializer.Write(this.joint_1);
            serializer.Write(this.joint_2);
            serializer.Write(this.joint_3);
            serializer.Write(this.joint_4);
            serializer.Write(this.joint_5);
            serializer.Write(this.joint_6);
            serializer.Write(this.goal_x);
            serializer.Write(this.goal_y);
            serializer.Write(this.goal_z);
        }

        public override string ToString()
        {
            return "ArmCommandMsg: " +
            "\ncommand: " + command.ToString() +
            "\nplanner: " + planner.ToString() +
            "\njoint_to_move: " + joint_to_move.ToString() +
            "\njoint_1: " + joint_1.ToString() +
            "\njoint_2: " + joint_2.ToString() +
            "\njoint_3: " + joint_3.ToString() +
            "\njoint_4: " + joint_4.ToString() +
            "\njoint_5: " + joint_5.ToString() +
            "\njoint_6: " + joint_6.ToString() +
            "\ngoal_x: " + goal_x.ToString() +
            "\ngoal_y: " + goal_y.ToString() +
            "\ngoal_z: " + goal_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
