//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.JacoArm
{
    [Serializable]
    public class ArmReportMsg : Message
    {
        public const string k_RosMessageName = "jaco_arm/ArmReport";
        public override string RosMessageName => k_RosMessageName;

        public bool running;
        public bool showing;
        public float joint_1;
        public float joint_2;
        public float joint_3;
        public float joint_4;
        public float joint_5;
        public float joint_6;
        public float goal_x;
        public float goal_y;
        public float goal_z;
        public float eef_p_x;
        public float eef_p_y;
        public float eef_p_z;
        public float eef_o_x;
        public float eef_o_y;
        public float eef_o_z;
        public float eef_o_w;

        public ArmReportMsg()
        {
            this.running = false;
            this.showing = false;
            this.joint_1 = 0.0f;
            this.joint_2 = 0.0f;
            this.joint_3 = 0.0f;
            this.joint_4 = 0.0f;
            this.joint_5 = 0.0f;
            this.joint_6 = 0.0f;
            this.goal_x = 0.0f;
            this.goal_y = 0.0f;
            this.goal_z = 0.0f;
            this.eef_p_x = 0.0f;
            this.eef_p_y = 0.0f;
            this.eef_p_z = 0.0f;
            this.eef_o_x = 0.0f;
            this.eef_o_y = 0.0f;
            this.eef_o_z = 0.0f;
            this.eef_o_w = 0.0f;
        }

        public ArmReportMsg(bool running, bool showing, float joint_1, float joint_2, float joint_3, float joint_4, float joint_5, float joint_6, float goal_x, float goal_y, float goal_z, float eef_p_x, float eef_p_y, float eef_p_z, float eef_o_x, float eef_o_y, float eef_o_z, float eef_o_w)
        {
            this.running = running;
            this.showing = showing;
            this.joint_1 = joint_1;
            this.joint_2 = joint_2;
            this.joint_3 = joint_3;
            this.joint_4 = joint_4;
            this.joint_5 = joint_5;
            this.joint_6 = joint_6;
            this.goal_x = goal_x;
            this.goal_y = goal_y;
            this.goal_z = goal_z;
            this.eef_p_x = eef_p_x;
            this.eef_p_y = eef_p_y;
            this.eef_p_z = eef_p_z;
            this.eef_o_x = eef_o_x;
            this.eef_o_y = eef_o_y;
            this.eef_o_z = eef_o_z;
            this.eef_o_w = eef_o_w;
        }

        public static ArmReportMsg Deserialize(MessageDeserializer deserializer) => new ArmReportMsg(deserializer);

        private ArmReportMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.running);
            deserializer.Read(out this.showing);
            deserializer.Read(out this.joint_1);
            deserializer.Read(out this.joint_2);
            deserializer.Read(out this.joint_3);
            deserializer.Read(out this.joint_4);
            deserializer.Read(out this.joint_5);
            deserializer.Read(out this.joint_6);
            deserializer.Read(out this.goal_x);
            deserializer.Read(out this.goal_y);
            deserializer.Read(out this.goal_z);
            deserializer.Read(out this.eef_p_x);
            deserializer.Read(out this.eef_p_y);
            deserializer.Read(out this.eef_p_z);
            deserializer.Read(out this.eef_o_x);
            deserializer.Read(out this.eef_o_y);
            deserializer.Read(out this.eef_o_z);
            deserializer.Read(out this.eef_o_w);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.running);
            serializer.Write(this.showing);
            serializer.Write(this.joint_1);
            serializer.Write(this.joint_2);
            serializer.Write(this.joint_3);
            serializer.Write(this.joint_4);
            serializer.Write(this.joint_5);
            serializer.Write(this.joint_6);
            serializer.Write(this.goal_x);
            serializer.Write(this.goal_y);
            serializer.Write(this.goal_z);
            serializer.Write(this.eef_p_x);
            serializer.Write(this.eef_p_y);
            serializer.Write(this.eef_p_z);
            serializer.Write(this.eef_o_x);
            serializer.Write(this.eef_o_y);
            serializer.Write(this.eef_o_z);
            serializer.Write(this.eef_o_w);
        }

        public override string ToString()
        {
            return "ArmReportMsg: " +
            "\nrunning: " + running.ToString() +
            "\nshowing: " + showing.ToString() +
            "\njoint_1: " + joint_1.ToString() +
            "\njoint_2: " + joint_2.ToString() +
            "\njoint_3: " + joint_3.ToString() +
            "\njoint_4: " + joint_4.ToString() +
            "\njoint_5: " + joint_5.ToString() +
            "\njoint_6: " + joint_6.ToString() +
            "\ngoal_x: " + goal_x.ToString() +
            "\ngoal_y: " + goal_y.ToString() +
            "\ngoal_z: " + goal_z.ToString() +
            "\neef_p_x: " + eef_p_x.ToString() +
            "\neef_p_y: " + eef_p_y.ToString() +
            "\neef_p_z: " + eef_p_z.ToString() +
            "\neef_o_x: " + eef_o_x.ToString() +
            "\neef_o_y: " + eef_o_y.ToString() +
            "\neef_o_z: " + eef_o_z.ToString() +
            "\neef_o_w: " + eef_o_w.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
