//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.JacoArm
{
    [Serializable]
    public class LearningStatsMsg : Message
    {
        public const string k_RosMessageName = "jaco_arm/LearningStats";
        public override string RosMessageName => k_RosMessageName;

        public int goals_reached;
        public int collision_resets;
        public int iteration;
        public int episode;
        public float ctrl_reward;
        public float approach_reward;
        public float orientation_reward;
        public float reward;

        public LearningStatsMsg()
        {
            this.goals_reached = 0;
            this.collision_resets = 0;
            this.iteration = 0;
            this.episode = 0;
            this.ctrl_reward = 0.0f;
            this.approach_reward = 0.0f;
            this.orientation_reward = 0.0f;
            this.reward = 0.0f;
        }

        public LearningStatsMsg(int goals_reached, int collision_resets, int iteration, int episode, float ctrl_reward, float approach_reward, float orientation_reward, float reward)
        {
            this.goals_reached = goals_reached;
            this.collision_resets = collision_resets;
            this.iteration = iteration;
            this.episode = episode;
            this.ctrl_reward = ctrl_reward;
            this.approach_reward = approach_reward;
            this.orientation_reward = orientation_reward;
            this.reward = reward;
        }

        public static LearningStatsMsg Deserialize(MessageDeserializer deserializer) => new LearningStatsMsg(deserializer);

        private LearningStatsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.goals_reached);
            deserializer.Read(out this.collision_resets);
            deserializer.Read(out this.iteration);
            deserializer.Read(out this.episode);
            deserializer.Read(out this.ctrl_reward);
            deserializer.Read(out this.approach_reward);
            deserializer.Read(out this.orientation_reward);
            deserializer.Read(out this.reward);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.goals_reached);
            serializer.Write(this.collision_resets);
            serializer.Write(this.iteration);
            serializer.Write(this.episode);
            serializer.Write(this.ctrl_reward);
            serializer.Write(this.approach_reward);
            serializer.Write(this.orientation_reward);
            serializer.Write(this.reward);
        }

        public override string ToString()
        {
            return "LearningStatsMsg: " +
            "\ngoals_reached: " + goals_reached.ToString() +
            "\ncollision_resets: " + collision_resets.ToString() +
            "\niteration: " + iteration.ToString() +
            "\nepisode: " + episode.ToString() +
            "\nctrl_reward: " + ctrl_reward.ToString() +
            "\napproach_reward: " + approach_reward.ToString() +
            "\norientation_reward: " + orientation_reward.ToString() +
            "\nreward: " + reward.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
