controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - j2n6s200_joint_1
      - j2n6s200_joint_2
      - j2n6s200_joint_3
      - j2n6s200_joint_4
      - j2n6s200_joint_5
      - j2n6s200_joint_6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - j2n6s200_joint_finger_1
      - j2n6s200_joint_finger_2
initial:  # Define initial robot poses per group
  - group: arm
    pose: start
  - group: gripper
    pose: open