# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.7
default_acceleration_scaling_factor: 0.3

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  j2n6s200_joint_1:
    has_velocity_limits: true
    max_velocity: 0.6283185307179586
    has_acceleration_limits: false
    max_acceleration: 0
  j2n6s200_joint_2:
    has_velocity_limits: true
    max_velocity: 0.6283185307179586
    has_acceleration_limits: false
    max_acceleration: 0
  j2n6s200_joint_3:
    has_velocity_limits: true
    max_velocity: 0.6283185307179586
    has_acceleration_limits: false
    max_acceleration: 0
  j2n6s200_joint_4:
    has_velocity_limits: true
    max_velocity: 0.8377580409572781
    has_acceleration_limits: false
    max_acceleration: 0
  j2n6s200_joint_5:
    has_velocity_limits: true
    max_velocity: 0.8377580409572781
    has_acceleration_limits: false
    max_acceleration: 0
  j2n6s200_joint_6:
    has_velocity_limits: true
    max_velocity: 0.8377580409572781
    has_acceleration_limits: false
    max_acceleration: 0
  j2n6s200_joint_finger_1:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  j2n6s200_joint_finger_2:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
